# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wizard(object):
    def setupUi(self, wizard):
        wizard.setObjectName("wizard")
        wizard.resize(676, 387)
        self.wizardPage_2 = QtWidgets.QWizardPage()
        self.wizardPage_2.setObjectName("wizardPage_2")
        self.layoutWidget = QtWidgets.QWidget(self.wizardPage_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 601, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.commandLinkButton_seq = QtWidgets.QCommandLinkButton(self.layoutWidget)
        self.commandLinkButton_seq.setMaximumSize(QtCore.QSize(200, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton_seq.setIcon(icon)
        self.commandLinkButton_seq.setIconSize(QtCore.QSize(48, 48))
        self.commandLinkButton_seq.setObjectName("commandLinkButton_seq")
        self.verticalLayout_3.addWidget(self.commandLinkButton_seq)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        wizard.addPage(self.wizardPage_2)
        self.wizardPage_3 = QtWidgets.QWizardPage()
        self.wizardPage_3.setObjectName("wizardPage_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.wizardPage_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 221, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.wizardPage_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(350, 40, 271, 281))
        self.plainTextEdit.setObjectName("plainTextEdit")
        wizard.addPage(self.wizardPage_3)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.layoutWidget2 = QtWidgets.QWidget(self.wizardPage2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 10, 351, 131))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        wizard.addPage(self.wizardPage2)

        self.retranslateUi(wizard)
        QtCore.QMetaObject.connectSlotsByName(wizard)

    def retranslateUi(self, wizard):
        _translate = QtCore.QCoreApplication.translate
        wizard.setWindowTitle(_translate("wizard", "Create new database"))
        self.commandLinkButton_seq.setText(_translate("wizard", "Choose source file"))
        self.label_5.setText(_translate("wizard", "No source file selected"))
        self.label_6.setText(_translate("wizard", "Enter a database name:"))
        self.label_2.setText(_translate("wizard", "Progress:"))
from . import sifi_2015_rc
